// Blue Salon storefront sample data (fictional listings, real brand names).
// Product imagery comes from the local /images folder — evening gowns and
// fine fashion jewellery, shot on white. Every product carries a gallery
// (images[]), colorHex swatch, editorial copy and spec details.
window.BS_DATA = (function () {
  const img = (file) => "images/" + file;

  const products = [
    { id: "zm-ivory-gown", vendor: "Zuhair Murad", name: "Crystal-Embellished Strapless Crepe Gown, Ivory",
      price: 28500, image: img("0_4d42c2f7-3d94-4330-8d41-384bbf740c8a_540x.webp"),
      badge: "New", badgeTone: "new", cat: "Gowns", type: "Evening", rating: 4.9, count: 14,
      color: "Ivory", colorHex: "#f1e9dc", sizes: ["6", "8", "10", "12"],
      images: [img("0_4d42c2f7-3d94-4330-8d41-384bbf740c8a_540x.webp")],
      desc: "Couture drama in ivory crepe — a strapless column scattered with hand-applied crystal motifs, gathered at the hip and split to the thigh. From the house that dresses the red carpet, made for the season's grandest invitations.",
      details: ["Stretch crepe · hand-applied crystals", "Strapless sweetheart bodice · boned", "Draped hip detail · front slit", "Concealed back zip", "Dry clean only", "Made in Lebanon"] },

    { id: "eliesaab-noir-gown", vendor: "Elie Saab", name: "Crystal Cascade Slip Gown, Noir",
      price: 19900, compareAt: 24900, badge: "-20%", badgeTone: "sale",
      image: img("0_72ed2cb0-f6df-46e1-aa85-33a64132db13_540x.webp"),
      cat: "Gowns", type: "Evening", rating: 4.8, count: 21,
      color: "Black", colorHex: "#1a1a1c", sizes: ["6", "8", "10", "12"],
      images: [img("0_72ed2cb0-f6df-46e1-aa85-33a64132db13_540x.webp")],
      desc: "A bias-cut column in inky cady, its neckline traced with a cascade of gold-set crystals. Quiet from afar, dazzling up close — evening dressing the Elie Saab way.",
      details: ["Silk-blend cady · bias cut", "Gold-set crystal cascade neckline", "Adjustable straps · low back", "Floor length · small train", "Dry clean only", "Made in Lebanon"] },

    { id: "leolin-dress", vendor: "Leo Lin", name: "Matilda Embroidered Tulle Gown — Blush Botanical",
      price: 2990, image: img("1_cbff2b7e-d52a-46e0-a986-89ed7f0083c9_540x.webp"),
      cat: "Gowns", type: "Evening", rating: 4.6, count: 22,
      color: "Blush", colorHex: "#e3c4bc", sizes: ["6", "8", "10", "12"],
      images: [img("1_cbff2b7e-d52a-46e0-a986-89ed7f0083c9_540x.webp")],
      desc: "Blouson sleeves and a sweeping column of embroidered tulle, blooming with blush botanicals and sequin light. Romantic, covered and made for warm-weather celebrations.",
      details: ["Embroidered tulle · sequin details", "Plunge V-neck · blouson sleeves", "Fully lined bodice and skirt", "Concealed back zip", "Dry clean only", "Designed in Australia"] },

    { id: "zm-gold-gown", vendor: "Zuhair Murad", name: "Sequin-Embellished Tulle Gown, Champagne Gold",
      price: 32000, badge: "Exclusive", badgeTone: "gold",
      image: img("1_d90af013-05a4-447c-b48b-e2f61584c227_540x.webp"),
      cat: "Gowns", type: "Evening", rating: 5, count: 9,
      color: "Gold", colorHex: "#c9a35e", sizes: ["6", "8", "10", "12"],
      images: [img("1_d90af013-05a4-447c-b48b-e2f61584c227_540x.webp")],
      desc: "Champagne-gold tulle worked entirely by hand with feathered sequin embroidery — a strapless ballgown that catches every light in the room. A Blue Salon exclusive for Qatar.",
      details: ["Hand-embroidered sequins on tulle", "Strapless corseted bodice", "Full A-line skirt · layered tulle", "Concealed back zip", "Blue Salon exclusive", "Made in Lebanon"] },

    { id: "swk-dazzling-swan", vendor: "Swarovski", name: "Dazzling Swan Bracelet, Rose-Gold Tone",
      price: 620, image: img("SWK128ACC04863_540x.webp"),
      cat: "Jewellery", type: "Bracelets", rating: 4.7, count: 118,
      color: "Rose gold", colorHex: "#d9a08c", sizes: ["OS"],
      images: [img("SWK128ACC04863_540x.webp")],
      desc: "The house swan, dazzling in pavé. A delicate rose-gold-tone chain carries the pink-crystal swan between sparkling stations — the everyday piece that never reads everyday.",
      details: ["Polished rose-tone finish", "Pavé crystal swan motif", "Lobster clasp · adjustable", "Length 17.5 cm", "Presented in Swarovski gift box"] },

    { id: "swk-sparkling-dance-set", vendor: "Swarovski", name: "Sparkling Dance Clover Set, Pink & Rose-Gold",
      price: 990, badge: "New", badgeTone: "new",
      image: img("SWK128ACC05524-3_540x.webp"),
      cat: "Jewellery", type: "Sets", rating: 4.8, count: 64,
      color: "Rose gold", colorHex: "#d9a08c", sizes: ["OS"],
      images: [img("SWK128ACC05524-3_540x.webp")],
      desc: "The signature Sparkling Dance stone — cut to tremble with every movement — set as a clover in pink crystal. Necklace and matching stud earrings, gift-ready in one box.",
      details: ["Necklace + stud earrings set", "Dancing crystal clover motif", "Polished rose-tone finish", "Necklace 38 cm + extender", "Presented in Swarovski gift box"] },

    { id: "lucabarra-heart-necklace", vendor: "Luca Barra", name: "Steel Necklace with Hearts & Pink Crystal",
      price: 240, soldOut: true,
      image: img("Luca_Barra_women_steel_necklace_with_pink_and_silver_hearts_and_crystal_CK2076-1_540x.webp"),
      cat: "Jewellery", type: "Necklaces", rating: 4.3, count: 37,
      color: "Silver", colorHex: "#cfd4da", sizes: ["OS"],
      images: [img("Luca_Barra_women_steel_necklace_with_pink_and_silver_hearts_and_crystal_CK2076-1_540x.webp")],
      desc: "A line of polished steel hearts descending to a single pink crystal heart. Light, playful and hypoallergenic — Italian fashion jewellery made for every day.",
      details: ["Polished stainless steel", "Pink crystal heart pendant", "Length 42 cm + 5 cm extender", "Hypoallergenic · nickel safe", "Made in Italy"] },

    { id: "lucabarra-flower-necklace", vendor: "Luca Barra", name: "Steel Necklace with Purple Zircon Flower",
      price: 260, image: img("Luca_Barra_women_steel_necklace_with_purple_zircon_flower_pendant_CK2195-1_540x.webp"),
      cat: "Jewellery", type: "Necklaces", rating: 4.4, count: 29,
      color: "Purple", colorHex: "#a678b8", sizes: ["OS"],
      images: [img("Luca_Barra_women_steel_necklace_with_purple_zircon_flower_pendant_CK2195-1_540x.webp")],
      desc: "A blossom of purple zircons on a whisper-fine steel chain, flanked by two floating crystals. Delicate colour that layers beautifully with everything.",
      details: ["Polished stainless steel", "Purple zircon flower pendant", "Two floating crystal stations", "Length 42 cm + 5 cm extender", "Made in Italy"] },

    { id: "cerruti-c-set", vendor: "Cerruti 1881", name: "Mother-of-Pearl 'C' Necklace, Earrings & Bracelet Set",
      price: 850, image: img("Full_Set_Overview_-CIJLN0013001-SET3_540x.webp"),
      cat: "Jewellery", type: "Sets", rating: 4.5, count: 42,
      color: "Gold", colorHex: "#d4af37", sizes: ["OS"],
      images: [img("Full_Set_Overview_-CIJLN0013001-SET3_540x.webp")],
      desc: "The maison's crystal-edged 'C' cradling a dome of mother-of-pearl — repeated across necklace, studs and station bracelet. A complete parure, gift-ready.",
      details: ["Necklace + earrings + bracelet", "Gold-tone plating · crystals", "Mother-of-pearl centre stones", "Necklace 42 cm · bracelet adjustable", "Presented in Cerruti 1881 gift box"] },

    { id: "justcavalli-earrings", vendor: "Just Cavalli", name: "Signature Chain Drop Earrings, Gold Tone",
      price: 380, compareAt: 475, badge: "-20%", badgeTone: "sale",
      image: img("JCA120ACC01009_2_copy_540x.webp"),
      cat: "Jewellery", type: "Earrings", rating: 4.2, count: 18,
      color: "Gold", colorHex: "#d4af37", sizes: ["OS"],
      images: [img("JCA120ACC01009_2_copy_540x.webp")],
      desc: "Mismatched by design — a pavé stud and a crystal heart, each trailing a fine chain finished with the Cavalli signature and a molten drop. Attitude, in gold tone.",
      details: ["Asymmetric pair · gold tone", "Pavé crystal studs", "Signature + drop pendants", "Butterfly fastening", "Presented in Just Cavalli pouch"] },

    { id: "fossil-star-bracelet", vendor: "Fossil", name: "Howlite Beaded Star Bolo Bracelet",
      price: 195, image: img("JF03115710-33_540x.webp"),
      cat: "Jewellery", type: "Bracelets", rating: 4.6, count: 83,
      color: "Ivory", colorHex: "#f1e9dc", sizes: ["OS"],
      images: [img("JF03115710-33_540x.webp")],
      desc: "White howlite beads on a grey cord, centred with a tiny gold-tone star and finished with a sliding bolo closure — stackable, adjustable, endlessly easy.",
      details: ["White howlite beads", "Gold-tone star centre", "Sliding bolo closure · adjustable", "Grey woven cord", "Fossil-branded keepsake tin"] },

    { id: "lesnereides-ring", vendor: "Les Néréides", name: "Cherry Blossom & Pink Stone Adjustable Ring",
      price: 425, badge: "Exclusive", badgeTone: "gold",
      image: img("ATBP604-1_540x.webp"),
      cat: "Jewellery", type: "Rings", rating: 4.7, count: 26,
      color: "Gold", colorHex: "#d4af37", sizes: ["OS"],
      images: [img("ATBP604-1_540x.webp")],
      desc: "Hand-enamelled cherry blossoms wrap the finger toward a faceted rose stone — Parisian storybook jewellery, finished in 14-carat gold plating and signed on the band.",
      details: ["Hand-enamelled blossom motifs", "Faceted rose-pink stone", "14-carat gold plating", "Adjustable open band", "Handmade in France"] },
    { id: "iceplay-runner-sneaker", vendor: "Ice Play", name: "Mesh Runner Sneaker, White & Silver",
      price: 690, badge: "New", badgeTone: "new",
      image: img("ICP123SHO00031_540x.webp"),
      cat: "Footwear", type: "Sneakers", rating: 4.5, count: 31,
      color: "White", colorHex: "#f6f5f1", sizes: ["36", "37", "38", "39", "40"],
      images: [img("ICP123SHO00031_540x.webp")],
      desc: "A clean white runner with mesh panels, silver trim and a graphic platform sole. Easy polish for travel days, weekend edits and pared-back tailoring.",
      details: ["Mesh and leather upper", "Silver heel and side trim", "Lace-up fastening", "Cushioned platform sole", "Rubber tread", "Made for everyday wear"] },

    { id: "lancel-pink-handle-bag", vendor: "Lancel", name: "Leather Top Handle Bag, Pink & Natural",
      price: 1890, badge: "New", badgeTone: "new",
      image: img("LNL123BAG00079_1_540x.webp"),
      cat: "Bags", type: "Handbags", rating: 4.8, count: 19,
      color: "Pink", colorHex: "#e94d98", sizes: ["OS"],
      images: [img("LNL123BAG00079_1_540x.webp")],
      desc: "A structured top-handle bag in confident pink leather, framed with natural tan trims and a detachable striped strap for hands-free styling.",
      details: ["Smooth leather body", "Top handles and detachable strap", "Zip side details", "Structured silhouette", "Internal slip pocket", "Presented with dust bag"] },

    { id: "orlandi-burgundy-braided-tote", vendor: "Orlandi Valentino", name: "Leather Braided Handle Tote, Burgundy",
      price: 1450,
      image: img("Orlandi_Valentino_Women_s_Leather_Braided_Handle_Tote_burgundy_angled_side_POV123BAG00286_1_540x.webp"),
      cat: "Bags", type: "Totes", rating: 4.6, count: 24,
      color: "Burgundy", colorHex: "#5a1724", sizes: ["OS"],
      images: [img("Orlandi_Valentino_Women_s_Leather_Braided_Handle_Tote_burgundy_angled_side_POV123BAG00286_1_540x.webp")],
      desc: "A soft burgundy leather tote with braided handles, folded side tabs and a long tassel pull. Rich colour, generous shape, quietly distinctive.",
      details: ["Leather outer", "Braided top handles", "Tassel detail", "Open tote shape", "Removable pouch detail", "Dust bag included"] },

    { id: "orlandi-black-shoulder-tote", vendor: "Orlandi Valentino", name: "Leather Shoulder Tote, Black",
      price: 1390,
      image: img("POV123BAG00290_1_540x.webp"),
      cat: "Bags", type: "Totes", rating: 4.5, count: 28,
      color: "Black", colorHex: "#090a0d", sizes: ["OS"],
      images: [img("POV123BAG00290_1_540x.webp")],
      desc: "A black leather shoulder tote with a polished circular fastening and clean architectural profile. Designed for office days and city evenings.",
      details: ["Smooth leather", "Dual shoulder handles", "Circular front hardware", "Structured base", "Zip compartment", "Dust bag included"] },

    { id: "schutz-patent-ankle-boot", vendor: "Schutz", name: "Patent Leather Ankle Boot, Oxblood",
      price: 980, compareAt: 1225, badge: "-20%", badgeTone: "sale",
      image: img("S2214700060002_02_540x.webp"),
      cat: "Footwear", type: "Boots", rating: 4.7, count: 34,
      color: "Oxblood", colorHex: "#651015", sizes: ["36", "37", "38", "39", "40"],
      images: [img("S2214700060002_02_540x.webp")],
      desc: "A glossy oxblood ankle boot with a sharp pointed toe and covered block heel. A high-impact finish for long dresses, denim and evening tailoring.",
      details: ["Patent leather upper", "Pointed toe", "Side zip fastening", "Covered block heel", "Leather lining", "Rubber-insert sole"] },

    { id: "schutz-black-ankle-sandal", vendor: "Schutz", name: "Ankle Strap Sandal, Black",
      price: 790,
      image: img("SHU123SHO01045_1_540x.webp"),
      cat: "Footwear", type: "Sandals", rating: 4.6, count: 41,
      color: "Black", colorHex: "#090a0d", sizes: ["36", "37", "38", "39", "40"],
      images: [img("SHU123SHO01045_1_540x.webp")],
      desc: "A minimal black ankle-strap sandal with a slim front band and refined high heel. The evening shoe that works across nearly every silhouette.",
      details: ["Leather upper", "Slim toe strap", "Adjustable ankle strap", "Stiletto heel", "Padded leather footbed", "Leather sole"] },

    { id: "godiva-centennial-chocolate-box", vendor: "Godiva", name: "Centennial Collection Chocolate Box",
      price: 220, badge: "New", badgeTone: "new",
      image: img("1782909937961.jpeg"),
      cat: "Gourmet", type: "Chocolates", rating: 4.9, count: 76,
      color: "Pink", colorHex: "#efb6c7", sizes: ["OS"],
      images: [img("1782909937961.jpeg")],
      desc: "A celebratory Godiva chocolate collection presented in a soft pink centennial box, with heritage pieces selected for gifting and after-dinner service.",
      details: ["Assorted Belgian chocolates", "Centennial edition packaging", "Milk, dark and white chocolate pieces", "Gift-ready presentation", "Store in a cool, dry place"] },
  ];

  const categories = [
    { label: "Women", img: "https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=900&q=80" },
    { label: "Men", img: "https://images.unsplash.com/photo-1516257984-b1b4d707412e?auto=format&fit=crop&w=900&q=80" },
    { label: "Bags", img: img("Orlandi_Valentino_Women_s_Leather_Braided_Handle_Tote_burgundy_angled_side_POV123BAG00286_1_540x.webp") },
    { label: "Footwear", img: img("S2214700060002_02_540x.webp") },
    { label: "Beauty", img: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=900&q=80" },
    { label: "Watches", img: "https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=900&q=80" },
    { label: "Luggage", img: "https://images.unsplash.com/photo-1565026057447-bc90a3dceb87?auto=format&fit=crop&w=900&q=80" },
    { label: "Gourmet", img: img("1782909937961.jpeg") },
  ];
  const nav = ["Women", "Men", "Kids", "Beauty", "Luggage", "Gourmet", "Home & Linen", "Gift"];
  return { products, categories, nav, hero: img("1_d90af013-05a4-447c-b48b-e2f61584c227_540x.webp") };
})();
